# Generated by Django 5.1.7 on 2025-03-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produts',
            new_name='Products',
        ),
    ]
